Question and answer models with tests
darialapina/thinknetica pull request #1
Opened 2017-05-16 13:27 UTC by darialapina

2017-05-16 17:25 UTC, vkurennov requested changes

2017-05-16 17:25 UTC, vkurennov commented on app/models/answer.rb
> +  validates :body, :question_id, presence: true
В 5-х рельсах не нужно валидирвовать поля ассоций, это происходит автоматически

2017-05-16 17:25 UTC, vkurennov commented on app/models/question.rb
> +	has_many :answers, dependent: :destroy
Настрой редактор на отступ ровно в 2 проблела. Причем, именно пробела, а не таба. Т.е. должна быть замена табов на пробелы, т.н. soft tabs. Найди в интернете как сделать soft tabs для твоего редактора

2017-05-16 17:25 UTC, vkurennov commented on spec/models/question_spec.rb
> +  it { should have_many :answers}
Опцию dependent тоже надо протестировать, shoulda-matchers это умеет

2017-05-16 18:12 UTC, darialapina commented on app/models/question.rb
> +	has_many :answers, dependent: :destroy
Интересно, как табы сюда пробрались...

2017-05-17 08:14 UTC, vkurennov approved these changes

2017-05-17 09:34 UTC, merged