7 ajax part 2
darialapina/thinknetica pull request #5
Opened 2017-05-28 22:31 UTC by darialapina

2017-05-29 08:40 UTC, vkurennov requested changes

2017-05-29 08:40 UTC, vkurennov commented on app/assets/javascripts/answers.js.coffee
> +      url: "/questions/" + question_id + "/answers/" + answer_id + "/set_best"
Если объявить ресурс answers как shallow в роутинге, то question_id не нужно будет передавать, его же можно уже в контроллере через ассоциации получить

2017-05-29 08:40 UTC, vkurennov commented on app/assets/javascripts/answers.js.coffee
> +        _method: "PUT"
Не нужно передавать метод PUT, если явно делаешь PATCH-запрос. Рельсы это делают для совместимости со старыми браузерами, но если ты из js шлешь запрос, то этого делать не нужно.

2017-05-29 08:40 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if @question.update(question_params)
А где проверка на автора?

2017-05-29 08:40 UTC, vkurennov commented on app/models/answer.rb
> +    self.question.answers.update_all(is_best: false)
Тут стоит применить [транзакцию](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html), чтобы изменения были атомарынми

2017-05-29 08:40 UTC, vkurennov commented on app/views/answers/create.js.erb
> +$('input.set-best-answer').on('change', function(e){
А вот такое дублирование - это уже очень плохо. Посмотри [вот это](http://connect.thinknetica.com/t/sovety-ajax-i-turbolinks/955) и сделай так, чтобы все работало и без дублирования

2017-05-29 08:40 UTC, vkurennov commented on app/views/answers/update.js.erb
> +  $('.edit-answer-link').click(function(e) {
И опять дублирование

2017-05-29 08:40 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(answer.is_best?).to be true
в rspec для методов-предикатов есть встроенная фича - их можно использовать как матчеры:

`expect(answer).to be_is_best`

Т.е. переносим метод в правую часть, добавляем be_ и убираем вопросительный знак. Правда, в твоем случае не очень красиво получается, потому что есть is, и это одна из причин, почему не рекомендуют использовать is в названии флагов.

2017-05-29 17:40 UTC, darialapina commented on app/controllers/questions_controller.rb
> +    if @question.update(question_params)
опа!

2017-05-29 17:42 UTC, darialapina commented on app/views/answers/create.js.erb
> +$('input.set-best-answer').on('change', function(e){
ага, уже утром поняла, что позорно профукала этап рефакторинга(

2017-05-29 18:16 UTC, darialapina commented on app/models/answer.rb
> +    self.question.answers.update_all(is_best: false)
Кстати, по этому месту вопрос.
Как правильно писать методы в таком случае? нужно ли дробить на методы для удобства тестирования?

2017-05-29 20:15 UTC, darialapina commented on app/assets/javascripts/answers.js.coffee
> +  $('.answers').on 'change', 'input.set-best-answer', (e) ->
только через on() получилось заставить работать
через события turbolinks не взлетело... не помогло добавление гема, ничего(
может руки кривые

2017-05-29 20:24 UTC, darialapina commented on app/assets/javascripts/answers.js.coffee
> +  $('.answers').on 'change', 'input.set-best-answer', (e) ->
загадка
напоследок ещё один раз попробовала, заработало. руки, действительно, кривые.
в последнем коммите всё ок

2017-05-29 21:44 UTC, darialapina commented on app/assets/javascripts/answers.js.coffee
> +  $('.answers').on 'change', 'input.set-best-answer', (e) ->
продолжу монолог)
но ведь я оставила навешивание действий через .on()... что же в итоге правильно работает?
это on() отрабатывает или связка on() с turbolinks?
явно нужно ещё почитать доки

2017-05-30 08:59 UTC, vkurennov commented on app/assets/javascripts/answers.js.coffee
> +  $('.answers').on 'change', 'input.set-best-answer', (e) ->
И то и другое. on навешивает событие глобально, и когда появляется новый элемент, обработчик уже есть и он срабатывает и на новые ответы. А загрузка через turbolinks нужна, потому что при переходе между страницами событие document.ready не будет исполняться

2017-05-30 09:01 UTC, vkurennov approved these changes

2017-05-30 09:01 UTC, vkurennov commented on app/models/answer.rb
> +      self.update(best: true)
транзакция откатывается только в случае исключения, поэтому здесь надо использовать `update!`, чтобы в случае ошибок было исключение и транзакция отменилась

2017-05-30 09:04 UTC, darialapina commented on app/models/answer.rb
> +      self.update(best: true)
готово)

2017-05-30 09:04 UTC, merged