9 various forms of ajax
darialapina/thinknetica pull request #7
Opened 2017-06-09 16:09 UTC by darialapina

2017-06-10 09:10 UTC, vkurennov requested changes

2017-06-10 09:10 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +	before_action :authenticate_user!
Что-то у тебя форматирование поехало

2017-06-10 09:10 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +      render json: @votable.rating
Тут и далее совсем жесть с форматированием какая-то.

2017-06-10 09:10 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +		if !current_user.author_of?(@votable)&&!@votable.has_vote_by?(current_user)
Ставь пробелы вокруг `&&`

2017-06-10 09:10 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +			current_user.votes.create({value: params[:value], votable_id: params[:votable_id], votable_type: params[:votable_type]})
У тебя уже загружен @votable, поэтому можно передавать не `votable_id`, `votable_type`, а просто `votable: @votable`. Работай не с полями, а с ассоциациями.

2017-06-10 09:10 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +	def reset
У меня кровь из глаз побежит от такого форматирования :-)

2017-06-10 09:10 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +    @vote = Vote.where(user_id: current_user.id).where(votable_id: params[:votable_id]).where(votable_type: params[:votable_type]).first
Можно все написать в одном where и вместо _id и _type указать просто votable

2017-06-10 09:10 UTC, vkurennov commented on spec/models/answer_spec.rb
> +  def has_vote_by?(user)
Зачем тут этот метод?

2017-06-10 19:02 UTC, darialapina commented on app/controllers/votes_controller.rb
> +	before_action :authenticate_user!
да что за беда! не понимаю, откуда берутся табы(
в настройках стоит интендация в пробелах, табунном по два пробела и всё такое... как они пробираются...

2017-06-10 19:02 UTC, darialapina commented on app/controllers/votes_controller.rb
> +		if !current_user.author_of?(@votable)&&!@votable.has_vote_by?(current_user)
ок

2017-06-10 19:07 UTC, darialapina commented on spec/models/answer_spec.rb
> +  def has_vote_by?(user)
ой, это я когда тест на него писала, временно вставила, чтобы перед глазами был) мда

2017-06-10 19:44 UTC, darialapina commented on app/controllers/votes_controller.rb
> +    @vote = Vote.where(user_id: current_user.id).where(votable_id: params[:votable_id]).where(votable_type: params[:votable_type]).first
В одном where - это понятно
А как тут быть с "вместо _id и _type указать просто votable"? я для метода reset не гружу votable

2017-06-11 11:17 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +    @vote = Vote.where(user_id: current_user.id).where(votable_id: params[:votable_id]).where(votable_type: params[:votable_type]).first
хм, ну тогда либо грузить votable, либо оставлять как есть

2017-06-11 11:17 UTC, vkurennov commented on spec/models/answer_spec.rb
> +  def has_vote_by?(user)
Тесты надо писать ДО кода ;-)

2017-06-11 11:18 UTC, vkurennov approved these changes

2017-06-11 20:48 UTC, darialapina commented on spec/models/answer_spec.rb
> +  def has_vote_by?(user)
я стараюсь, в 95% случаев это даже получается!
но порой вот подобные методы в моделях появляются сами))))

2017-06-11 21:27 UTC, merged